// Curated Unsplash imagery — real interior/exterior photos.
// Format kept consistent so cards crop cleanly.
const u = (id: string, w = 1600) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

const IMG = {
  livingA: u("photo-1484101403633-562f891dc89a"),
  livingB: u("photo-1493809842364-78817add7ffb"),
  livingC: u("photo-1502672260266-1c1ef2d93688"),
  livingD: u("photo-1560185007-cde436f6a4d0"),
  livingE: u("photo-1505693416388-ac5ce068fe85"),
  kitchenA: u("photo-1556909114-f6e7ad7d3136"),
  kitchenB: u("photo-1560448204-e02f11c3d0e2"),
  kitchenC: u("photo-1556909202-f6f6402ea3c2"),
  bedA: u("photo-1505691938895-1758d7feb511"),
  bedB: u("photo-1540518614846-7eded433c457"),
  bedC: u("photo-1522771739844-6a9f6d5f14af"),
  bedD: u("photo-1616594039964-ae9021a400a0"),
  bathA: u("photo-1552321554-5fefe8c9ef14"),
  bathB: u("photo-1600585154340-be6161a56a0c"),
  studio: u("photo-1554995207-c18c203602cb"),
  loft: u("photo-1522444195799-478538b28823"),
  balcony: u("photo-1502005229762-cf1b2da7c5d6"),
  exteriorA: u("photo-1545324418-cc1a3fa10c00"),
  exteriorB: u("photo-1512917774080-9991f1c4c750"),
  townhouse: u("photo-1568605114967-8130f3a36994"),
  house: u("photo-1494526585095-c41746248156"),
  condo: u("photo-1486406146926-c627a92ad1ab"),
  modernA: u("photo-1502672023488-70e25813eb80"),
  modernB: u("photo-1560448075-bb485b067938"),
  view: u("photo-1502673530728-f79b4cab31b1"),
};

export type Property = {
  id: string;
  title: string;
  neighborhood: string;
  city: string;
  price: number;
  beds: number;
  baths: number;
  sqft: number;
  type: "Loft" | "Condo" | "Apartment" | "Townhouse" | "Studio" | "House";
  images: string[];
  cover: string;
  lat?: number;
  available: string; // ISO date
  leaseLengths: ("month" | "6mo" | "12mo")[];
  amenities: string[];
  pets: boolean;
  parking: boolean;
  laundry: boolean;
  gym: boolean;
  furnished: boolean;
  rating: number;
  reviews: number;
  host: { name: string; verified: boolean; since: string; avatar: string };
  highlight?: string; // editorial tag
  description: string;
};

const host = (name: string, since: string, seed: number) => ({
  name,
  verified: true,
  since,
  avatar: `https://i.pravatar.cc/120?img=${seed}`,
});

export const properties: Property[] = [
  {
    id: "king-west-loft-27",
    title: "Sun-drenched King West Loft",
    neighborhood: "King West",
    city: "Toronto",
    price: 2450,
    beds: 1,
    baths: 1,
    sqft: 740,
    type: "Loft",
    images: [IMG.loft, IMG.livingA, IMG.kitchenA, IMG.bedA, IMG.bathA],
    cover: IMG.loft,
    available: "2026-05-01",
    leaseLengths: ["12mo", "6mo"],
    amenities: ["In-suite laundry", "Concierge", "Rooftop", "Bike storage", "Pet-friendly", "Parking"],
    pets: true,
    parking: true,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.92,
    reviews: 128,
    host: host("Mira Singh", "2021", 47),
    highlight: "Featured",
    description:
      "Loft-style living in the heart of King West. Soaring 11ft ceilings, exposed brick, and floor-to-ceiling windows that pour light into a quiet bedroom alcove. Steps to TIFF, the waterfront, and the streetcar.",
  },
  {
    id: "annex-studio-412",
    title: "Annex Studio · Bright & Cozy",
    neighborhood: "The Annex",
    city: "Toronto",
    price: 1875,
    beds: 0,
    baths: 1,
    sqft: 410,
    type: "Studio",
    images: [IMG.studio, IMG.kitchenB, IMG.bathB, IMG.livingC],
    cover: IMG.studio,
    available: "2026-05-15",
    leaseLengths: ["12mo"],
    amenities: ["Furnished", "Heat included", "Hardwood", "Laundry on floor"],
    pets: false,
    parking: false,
    laundry: true,
    gym: false,
    furnished: true,
    rating: 4.78,
    reviews: 64,
    host: host("Westmount Holdings", "2019", 12),
    description:
      "A handsome studio in a heritage Annex walk-up, fully furnished. Walk to U of T, Bloor Cinema, and the best coffee in the city. Heat and water included.",
  },
  {
    id: "liberty-village-2br-88",
    title: "Liberty Village 2BR with Skyline View",
    neighborhood: "Liberty Village",
    city: "Toronto",
    price: 2890,
    beds: 2,
    baths: 2,
    sqft: 920,
    type: "Condo",
    images: [IMG.view, IMG.livingB, IMG.kitchenA, IMG.bedB, IMG.balcony],
    cover: IMG.view,
    available: "2026-06-01",
    leaseLengths: ["12mo"],
    amenities: ["Gym", "Pool", "Concierge", "Parking", "Balcony", "In-suite laundry"],
    pets: true,
    parking: true,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.85,
    reviews: 91,
    host: host("Joon Park", "2020", 33),
    highlight: "Skyline view",
    description:
      "Floor-to-ceiling windows on the 32nd floor frame the entire skyline. Two split bedrooms, a chef's kitchen, and a generous wrap balcony. Building has saltwater pool and 24-hr concierge.",
  },
  {
    id: "leslieville-townhouse-12",
    title: "Leslieville Townhouse with Patio",
    neighborhood: "Leslieville",
    city: "Toronto",
    price: 3450,
    beds: 3,
    baths: 2,
    sqft: 1340,
    type: "Townhouse",
    images: [IMG.townhouse, IMG.livingD, IMG.kitchenC, IMG.bedC, IMG.bathA],
    cover: IMG.townhouse,
    available: "2026-05-01",
    leaseLengths: ["12mo"],
    amenities: ["Private patio", "Parking", "Pet-friendly", "Laundry", "Backyard"],
    pets: true,
    parking: true,
    laundry: true,
    gym: false,
    furnished: false,
    rating: 4.96,
    reviews: 38,
    host: host("Helena Cross", "2018", 22),
    highlight: "Move-in ready",
    description:
      "A three-bedroom townhouse on a quiet Leslieville street. South-facing patio, parking, and a chef's kitchen that opens to the dining room. Steps to Queen East cafés.",
  },
  {
    id: "yorkville-condo-9",
    title: "Yorkville Designer Condo",
    neighborhood: "Yorkville",
    city: "Toronto",
    price: 4200,
    beds: 2,
    baths: 2,
    sqft: 1080,
    type: "Condo",
    images: [IMG.modernA, IMG.kitchenB, IMG.livingE, IMG.bedD, IMG.balcony],
    cover: IMG.modernA,
    available: "2026-05-20",
    leaseLengths: ["12mo"],
    amenities: ["Concierge", "Gym", "Spa", "Valet parking", "Wine cellar"],
    pets: true,
    parking: true,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.99,
    reviews: 26,
    host: host("Yorkville Estates", "2017", 14),
    highlight: "Editor's pick",
    description:
      "Designer-finished suite in a five-star Yorkville building. Walk-out terrace, primary suite with ensuite, and full-floor amenities. Steps to Holts and Whole Foods.",
  },
  {
    id: "cabbagetown-garden-3",
    title: "Cabbagetown Garden Suite",
    neighborhood: "Cabbagetown",
    city: "Toronto",
    price: 1620,
    beds: 1,
    baths: 1,
    sqft: 520,
    type: "Apartment",
    images: [IMG.house, IMG.livingC, IMG.bedA],
    cover: IMG.house,
    available: "2026-06-15",
    leaseLengths: ["12mo", "6mo"],
    amenities: ["Garden access", "Heat included", "Laundry"],
    pets: false,
    parking: false,
    laundry: true,
    gym: false,
    furnished: false,
    rating: 4.62,
    reviews: 41,
    host: host("Helena Cross", "2018", 22),
    description:
      "A character garden suite in a Victorian on a tree-lined Cabbagetown street. Private entrance, leafy backyard, and tons of charm.",
  },
  {
    id: "queen-west-loft-44",
    title: "Queen West Industrial Loft",
    neighborhood: "Queen West",
    city: "Toronto",
    price: 2750,
    beds: 1,
    baths: 1,
    sqft: 820,
    type: "Loft",
    images: [IMG.modernB, IMG.kitchenA, IMG.livingA, IMG.bedB],
    cover: IMG.modernB,
    available: "2026-05-01",
    leaseLengths: ["12mo"],
    amenities: ["Concrete floors", "Gym", "Rooftop", "Bike storage"],
    pets: true,
    parking: false,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.81,
    reviews: 73,
    host: host("Trinity Lofts", "2020", 8),
    highlight: "Newly listed",
    description:
      "Industrial chic loft in a converted Queen West warehouse. Polished concrete, soaring ceilings, and a gym with skyline views.",
  },
  {
    id: "junction-house-77",
    title: "The Junction · Family House",
    neighborhood: "The Junction",
    city: "Toronto",
    price: 3950,
    beds: 4,
    baths: 3,
    sqft: 1980,
    type: "House",
    images: [IMG.exteriorB, IMG.livingD, IMG.kitchenC, IMG.bedC, IMG.bathB],
    cover: IMG.exteriorB,
    available: "2026-07-01",
    leaseLengths: ["12mo"],
    amenities: ["Backyard", "Parking (2)", "Finished basement", "Pet-friendly"],
    pets: true,
    parking: true,
    laundry: true,
    gym: false,
    furnished: false,
    rating: 4.88,
    reviews: 19,
    host: host("Marcus Lee", "2019", 51),
    description:
      "Four bedrooms, three baths, and a backyard built for summer. Newly renovated kitchen, primary suite with walk-in, and a finished lower level.",
  },
  {
    id: "harbourfront-studio-21",
    title: "Harbourfront Studio · Lake Views",
    neighborhood: "Harbourfront",
    city: "Toronto",
    price: 1995,
    beds: 0,
    baths: 1,
    sqft: 480,
    type: "Studio",
    images: [IMG.studio, IMG.balcony, IMG.kitchenB],
    cover: IMG.balcony,
    available: "2026-05-01",
    leaseLengths: ["12mo", "month"],
    amenities: ["Lake view", "Pool", "Gym", "Concierge", "Furnished"],
    pets: false,
    parking: false,
    laundry: true,
    gym: true,
    furnished: true,
    rating: 4.74,
    reviews: 112,
    host: host("Harbour Living", "2018", 28),
    description:
      "Lake Ontario views from a sun-flooded studio. Murphy bed, designer kitchenette, and a balcony to watch the sailboats. Furnished and ready.",
  },
  {
    id: "rosedale-condo-5",
    title: "Rosedale Pre-War Apartment",
    neighborhood: "Rosedale",
    city: "Toronto",
    price: 3250,
    beds: 2,
    baths: 1,
    sqft: 980,
    type: "Apartment",
    images: [IMG.livingE, IMG.kitchenC, IMG.bedD, IMG.bathA],
    cover: IMG.livingE,
    available: "2026-06-01",
    leaseLengths: ["12mo"],
    amenities: ["Original hardwood", "Heat included", "Storage", "Bike storage"],
    pets: true,
    parking: false,
    laundry: false,
    gym: false,
    furnished: false,
    rating: 4.79,
    reviews: 47,
    host: host("Bayview Holdings", "2015", 19),
    description:
      "Two bedrooms in a beautifully maintained pre-war Rosedale building. Crown moulding, original hardwood, and quiet leafy streets steps away.",
  },
  {
    id: "parkdale-1br-19",
    title: "Parkdale 1BR · Walk-out Balcony",
    neighborhood: "Parkdale",
    city: "Toronto",
    price: 2050,
    beds: 1,
    baths: 1,
    sqft: 620,
    type: "Apartment",
    images: [IMG.balcony, IMG.livingB, IMG.bedA, IMG.kitchenA],
    cover: IMG.livingB,
    available: "2026-05-01",
    leaseLengths: ["12mo"],
    amenities: ["Balcony", "Pet-friendly", "Heat included", "Bike storage"],
    pets: true,
    parking: false,
    laundry: true,
    gym: false,
    furnished: false,
    rating: 4.7,
    reviews: 56,
    host: host("West End Co.", "2020", 39),
    description:
      "Charming Parkdale 1BR with a generous walk-out balcony. Heat included, pet-friendly, and a 2-min walk to the streetcar.",
  },
  {
    id: "distillery-loft-3",
    title: "Distillery District Loft",
    neighborhood: "Distillery District",
    city: "Toronto",
    price: 2950,
    beds: 1,
    baths: 1,
    sqft: 880,
    type: "Loft",
    images: [IMG.loft, IMG.livingD, IMG.kitchenB, IMG.bedB],
    cover: IMG.livingD,
    available: "2026-06-01",
    leaseLengths: ["12mo"],
    amenities: ["Exposed brick", "Concierge", "Gym", "Pet-friendly", "Parking"],
    pets: true,
    parking: true,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.9,
    reviews: 84,
    host: host("Distillery Collective", "2017", 60),
    highlight: "Pet-friendly",
    description:
      "Hard loft with exposed brick and timber beams in the iconic Distillery District. Cobblestone streets, art galleries, and restaurants at your door.",
  },
  {
    id: "midtown-2br-101",
    title: "Yonge & Eglinton 2BR",
    neighborhood: "Midtown",
    city: "Toronto",
    price: 2680,
    beds: 2,
    baths: 1,
    sqft: 850,
    type: "Condo",
    images: [IMG.condo, IMG.kitchenC, IMG.bedC, IMG.bathB, IMG.balcony],
    cover: IMG.condo,
    available: "2026-05-01",
    leaseLengths: ["12mo"],
    amenities: ["Gym", "Concierge", "Subway access", "Laundry"],
    pets: false,
    parking: true,
    laundry: true,
    gym: true,
    furnished: false,
    rating: 4.66,
    reviews: 72,
    host: host("Eglinton Properties", "2016", 17),
    description:
      "Smartly laid-out two-bedroom steps from the Eglinton subway. Bright south exposure and a fully equipped gym in the building.",
  },
  {
    id: "beaches-cottage-9",
    title: "The Beaches · Lake-side Cottage",
    neighborhood: "The Beaches",
    city: "Toronto",
    price: 3100,
    beds: 2,
    baths: 1,
    sqft: 1100,
    type: "House",
    images: [IMG.exteriorA, IMG.livingC, IMG.bedA, IMG.kitchenA],
    cover: IMG.exteriorA,
    available: "2026-06-15",
    leaseLengths: ["12mo"],
    amenities: ["Backyard", "Parking", "Pet-friendly", "Steps to lake"],
    pets: true,
    parking: true,
    laundry: true,
    gym: false,
    furnished: false,
    rating: 4.95,
    reviews: 31,
    host: host("Audrey Tan", "2019", 44),
    description:
      "A cottage-style two-bedroom one block from the boardwalk. Sunny breakfast nook, newly renovated kitchen, and a backyard for summer dinners.",
  },
];

export const neighborhoods = Array.from(
  new Set(properties.map((p) => p.neighborhood))
).sort();

export const propertyTypes = [
  "Loft",
  "Condo",
  "Apartment",
  "Townhouse",
  "Studio",
  "House",
] as const;

export function findProperty(id: string) {
  return properties.find((p) => p.id === id);
}

// Editorial rails for the Dashboard + Discover.
export function rail(name: string, predicate: (p: Property) => boolean) {
  return { name, items: properties.filter(predicate) };
}

export const dashboardRails = [
  rail("Recommended for you", (p) => p.rating >= 4.85),
  rail("Move-in ready May 1", (p) => p.available === "2026-05-01"),
  rail("Pet-friendly homes", (p) => p.pets),
  rail("Newly listed", (p) =>
    ["queen-west-loft-44", "yorkville-condo-9", "midtown-2br-101"].includes(p.id)
  ),
];
